imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
  nodes:
    coverage:
      tests:
        override:
          - command: make testtravis
            coverage:
              file: build/coverage.clover

              # These formats are supported:
              # clover, cobertura, jacoco, python-cc, ruby-cc, go-cc, lcov
              format: "php-clover"
