imports:
  - php

filter:
  excluded_paths: [vendor/, test/, htdocs/js/OpenLayers.js]

build:
  environment:
    php: 7.2
  dependencies:
    before:
      - command: "rm -rf build mkdir build"
    after:
      - "composer require --dev phpunit/phpunit"

  nodes:
    coverage:
      tests:
        override:
        - command: "vendor/bin/phpunit --configuration .phpunit.xml"
          coverage:
            file: "build/coverage.clover"
            format: "php-clover"
